### ISSUE TITLE
install anslible form cygwin

### ISSUE THREAD

**Issue by lukasruoff** [meengit/vagrant-ansible-windows#3]
you have to install ansible from cygwin and not from pip. This can result in installation errors

```text
Traceback (most recent call last):
  File "/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/site-packages/pip/__main__.py", line 31, in <module>
    sys.exit(_main())
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 71, in main
    return command.main(cmd_args)
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 104, in main
    return self._main(args)
  File "/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/command_context.py", line 22, in main_context
    yield
  File "/lib/python3.8/contextlib.py", line 525, in __exit__
    raise exc_details[1]
  File "/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.8/site-packages/pip/_internal/utils/temp_dir.py", line 75, in tempdir_registry
    yield _tempdir_registry
  File "/lib/python3.8/contextlib.py", line 510, in __exit__
    if cb(*exc_details):
  File "/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/usr/lib/python3.8/site-packages/pip/_internal/utils/temp_dir.py", line 37, in global_tempdir_manager
    _tempdir_manager = old_tempdir_manager
  File "/lib/python3.8/contextlib.py", line 525, in __exit__
    raise exc_details[1]
  File "/lib/python3.8/contextlib.py", line 510, in __exit__
    if cb(*exc_details):
  File "/usr/lib/python3.8/site-packages/pip/_internal/utils/temp_dir.py", line 165, in __exit__
    self.cleanup()
  File "/usr/lib/python3.8/site-packages/pip/_internal/utils/temp_dir.py", line 184, in cleanup
    rmtree(self._path)
  File "/usr/lib/python3.8/site-packages/pip/_vendor/tenacity/__init__.py", line 339, in wrapped_f
    return self(f, *args, **kw)
  File "/usr/lib/python3.8/site-packages/pip/_vendor/tenacity/__init__.py", line 430, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/lib/python3.8/site-packages/pip/_vendor/tenacity/__init__.py", line 367, in iter
    return fut.result()
  File "/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/site-packages/pip/_vendor/tenacity/__init__.py", line 433, in __call__
    result = fn(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 135, in rmtree
    shutil.rmtree(dir, ignore_errors=ignore_errors, onerror=rmtree_errorhandler)
  File "/lib/python3.8/shutil.py", line 718, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/lib/python3.8/shutil.py", line 655, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/lib/python3.8/shutil.py", line 655, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/lib/python3.8/shutil.py", line 655, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  [Previous line repeated 1 more time]
  File "/lib/python3.8/shutil.py", line 673, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
```

**Comment by meengit** [comment]
@lukasruoff, thank you very much for reporting this. I added the installation via pip.
